%YAML 1.2
---
learning_rate: 0.01
optim: SGD
batch_size: 1
nb_epoch: 1 
n_layers: 12
hidden_num: 100
activation: relu 
loss_weight: ave
adaptive_weight: False
data: susy
hedge: False
model: MLP
input_size: 18
log: log_mlp12
